server:
  port: 8081

spring:
  datasource:
    password: 159375
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    #日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID


jwt:
  #JWT存储的请求头
  tokenHeader: Authorization
  #JWT 加解密使用的秘钥
  secret: yeb-secret
  #JWT的超期限时间
  expiration: 604800
  #JWT 负载中拿到开头
  tokenHead: Bearer